import Head from "next/head";

function About () {
    return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About Page</h1>
        <p>This is About page.</p>
      </main>
      </div>
    )
  }
  
  export default About;